import { motion } from "motion/react";
import { FiArrowUpRight, FiMapPin } from "react-icons/fi";

const skills = ["React.js", "Node.js", "Magento 2", "Shopify", "WordPress", "PHP", "MongoDB", "AWS", "UI/UX", "Performance"];
const stats = [{ value: "8+", label: "Years experience" }, { value: "15+", label: "Live projects" }, { value: "25%", label: "Conversion uplift" }, { value: "40%", label: "Performance gains" }];

const About = () => <section id="about" className="section-wrap">
  <div className="grid items-end gap-8 lg:grid-cols-[1.15fr_.85fr]"><div><p className="section-kicker">Beyond the hero</p><h2 className="section-title max-w-3xl leading-tight">I turn complex digital challenges into <span className="gradient-text">simple, high-performing experiences.</span></h2></div><p className="section-lead lg:ml-auto">Full-stack web developer specializing in scalable commerce, polished interfaces, and reliable delivery for ambitious brands.</p></div>
  <div className="mt-12 grid gap-4 md:grid-cols-12">
    <motion.article whileHover={{ y: -4 }} className="glass-card relative overflow-hidden rounded-[1.75rem] p-7 md:col-span-7 md:p-9"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-violet-600/20 blur-3xl" /><div className="relative"><span className="inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/[.07] px-3 py-1 text-xs text-emerald-200"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300" />Available for select projects</span><h3 className="mt-10 text-2xl font-medium md:text-3xl">Hi, I’m Shiv Kumar Jha.</h3><p className="mt-4 max-w-xl leading-7 text-neutral-400">I’ve spent 8+ years designing and deploying e-commerce platforms across Magento, Shopify, WordPress, and the MERN stack—supporting 50K+ monthly visitors and millions in online revenue.</p><a href="#contact" className="mt-8 inline-flex items-center gap-2 text-sm font-medium text-white">Let’s work together <FiArrowUpRight /></a></div></motion.article>
    <article className="glass-card rounded-[1.75rem] p-7 md:col-span-5 md:p-9"><FiMapPin className="text-2xl text-cyan-300" /><h3 className="mt-8 text-2xl">New Delhi, India</h3><p className="mt-3 leading-7 text-neutral-400">Working remotely with teams worldwide and open to on-site opportunities across Delhi-NCR.</p><div className="mt-9 border-t border-white/10 pt-6 text-sm text-neutral-500">IST · UTC +05:30</div></article>
    <article className="glass-card rounded-[1.75rem] p-7 md:col-span-5 md:p-9"><p className="text-sm text-neutral-500">Selected capabilities</p><div className="mt-6 flex flex-wrap gap-2">{skills.map((skill) => <span key={skill} className="rounded-full border border-white/10 bg-white/[.04] px-3.5 py-2 text-sm text-neutral-300">{skill}</span>)}</div></article>
    <article className="glass-card grid grid-cols-2 overflow-hidden rounded-[1.75rem] md:col-span-7">{stats.map((stat) => <div key={stat.label} className="border-b border-r border-white/10 p-6 md:p-8"><strong className="text-3xl font-semibold gradient-text md:text-4xl">{stat.value}</strong><p className="mt-2 text-sm text-neutral-500">{stat.label}</p></div>)}</article>
  </div>
</section>;
export default About;
